theme: jekyll-theme-minimal
title: Holly has a site for things
description: "Personal website for Holly Stotelmyer- software engineer, [podcaster](https://www.b3cpod.com), dovahkiin."
logo: img/hollyid1.png
